# Generated by Django 6.0.7 on 2026-07-17 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0010_product_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("amazon_jp", "Amazon Japan"),
                            ("qoo10_jp", "Qoo10 Japan"),
                            ("manual", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_product_id", models.CharField(max_length=120)),
                ("source_url", models.URLField(max_length=1000)),
                ("canonical_url", models.URLField(max_length=1000)),
                (
                    "source_price_jpy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("source_currency", models.CharField(default="JPY", max_length=10)),
                (
                    "source_availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "source_stock_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "external_image_url",
                    models.URLField(blank=True, max_length=1500, null=True),
                ),
                (
                    "affiliate_url",
                    models.URLField(blank=True, max_length=1500, null=True),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("data_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never synced"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        default="never",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_info",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_price_jpy",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "calculated_price_usd",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "previous_product_price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("calculation_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="shop.product",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="product_sources.productsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("product_id", models.CharField(blank=True, max_length=100)),
                ("provider", models.CharField(blank=True, max_length=30)),
                ("source_product_id", models.CharField(blank=True, max_length=120)),
                ("dry_run", models.BooleanField(default=False)),
                ("input_summary", models.JSONField(default=dict)),
                ("result_summary", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=30)),
                ("source_category", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("sync", "Sync"),
                            ("reprice", "Reprice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False)),
                ("total", models.PositiveIntegerField(default=0)),
                ("succeeded", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=["provider", "sync_status"],
                name="product_sou_provide_937c92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=["last_synced_at"], name="product_sou_last_sy_e81393_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsource",
            constraint=models.UniqueConstraint(
                fields=("provider", "source_product_id"),
                name="uq_product_source_provider_product_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcecategorymapping",
            constraint=models.UniqueConstraint(
                fields=("provider", "source_category"),
                name="uq_source_category_mapping",
            ),
        ),
    ]
