# Generated by Django 6.0.7 on 2026-07-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_concierge_session_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Review"),
                    ("published", "Published"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="published",
                max_length=20,
            ),
        ),
    ]
