# Generated by Django 6.0.7 on 2026-08-06 02:55

from decimal import Decimal, InvalidOperation, ROUND_HALF_UP

from django.db import migrations, models


def backfill_pricing_inputs(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductPriceHistory = apps.get_model('product_sources', 'ProductPriceHistory')
    populated_ids = set()

    def number(value):
        return float(
            Decimal(value).quantize(Decimal('0.0001'), rounding=ROUND_HALF_UP)
        )

    histories = ProductPriceHistory.objects.order_by('product_id', '-created_at')
    for history in histories.iterator():
        if history.product_id in populated_ids:
            continue
        try:
            product = Product.objects.get(pk=history.product_id)
            snapshot = history.calculation_snapshot or {}
            source_currency = str(snapshot.get('source_currency') or 'JPY').upper()
            source_price = Decimal(str(snapshot['source_price']))
            source_price_vnd = Decimal(str(snapshot['source_price_vnd']))
            source_to_vnd_rate = Decimal(str(snapshot['source_to_vnd_rate']))
            source_buffer_vnd = Decimal(str(snapshot.get('source_buffer_vnd') or 0))
            usd_vnd_rate = Decimal(str(snapshot.get('usd_vnd_rate') or 25000))
            light_shipping_vnd = Decimal(str(snapshot.get('light_shipping_vnd') or 0))
            heavy_shipping_per_kg_vnd = Decimal(
                str(snapshot.get('heavy_shipping_per_kg_vnd') or 0)
            )
            heavy_weight_threshold_kg = Decimal(
                str(snapshot.get('heavy_weight_threshold_kg') or 0)
            )
            weight = Decimal(str(product.weight or 0))
        except (
            KeyError,
            InvalidOperation,
            TypeError,
            ValueError,
            Product.DoesNotExist,
        ):
            continue

        shipping_vnd = (
            weight * heavy_shipping_per_kg_vnd
            if weight > heavy_weight_threshold_kg
            else light_shipping_vnd
        )
        total_cost_vnd = source_price_vnd + source_buffer_vnd + shipping_vnd
        selling_price_vnd = Decimal(str(history.calculated_price_usd)) * usd_vnd_rate
        margin = (
            max(
                ((selling_price_vnd / total_cost_vnd) - Decimal('1'))
                * Decimal('100'),
                Decimal('0'),
            )
            if total_cost_vnd > 0
            else Decimal('0')
        )
        shipping_per_kg = shipping_vnd / weight if weight > 0 else Decimal('0')

        if source_currency not in {'JPY', 'USD'}:
            source_currency = 'USD'
            source_price = (
                source_price_vnd / usd_vnd_rate
                if usd_vnd_rate > 0
                else Decimal('0')
            )
            source_to_vnd_rate = usd_vnd_rate

        Product.objects.filter(pk=product.pk).update(pricing_inputs={
            'originCost': number(source_price),
            'originCurrency': source_currency,
            'exchangeRate': number(source_to_vnd_rate),
            'taxJapanPercent': 0,
            'taxVietnamVnd': 0,
            'shipInternationalPerKgVnd': number(shipping_per_kg),
            'shipJapanLocalVnd': 0,
            'shipVietnamLocalVnd': 0,
            'hiddenCostVnd': number(source_buffer_vnd),
            'profitMarginPercent': number(margin),
            'usdToVndRate': number(usd_vnd_rate),
        })
        populated_ids.add(product.pk)

    # Exact historic calculator inputs never existed for ordinary products.
    # Preserve their known total cost and selling price as a neutral USD setup.
    for product in Product.objects.exclude(pk__in=populated_ids).iterator():
        try:
            cost_vnd = Decimal(str(product.cost_price_vnd or 0))
            price_usd = Decimal(str(product.price or 0))
        except (InvalidOperation, TypeError, ValueError):
            continue
        if cost_vnd <= 0:
            continue
        usd_vnd_rate = Decimal('25000')
        selling_vnd = price_usd * usd_vnd_rate
        margin = max(
            ((selling_vnd / cost_vnd) - Decimal('1')) * Decimal('100'),
            Decimal('0'),
        )
        Product.objects.filter(pk=product.pk).update(pricing_inputs={
            'originCost': number(cost_vnd / usd_vnd_rate),
            'originCurrency': 'USD',
            'exchangeRate': number(usd_vnd_rate),
            'taxJapanPercent': 0,
            'taxVietnamVnd': 0,
            'shipInternationalPerKgVnd': 0,
            'shipJapanLocalVnd': 0,
            'shipVietnamLocalVnd': 0,
            'hiddenCostVnd': 0,
            'profitMarginPercent': number(margin),
            'usdToVndRate': number(usd_vnd_rate),
        })


class Migration(migrations.Migration):

    dependencies = [
        ('product_sources', '0001_initial'),
        ('shop', '0023_birthday_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_inputs',
            field=models.JSONField(blank=True, default=dict, help_text='Saved admin pricing-calculator inputs for subsequent edits.'),
        ),
        migrations.RunPython(
            backfill_pricing_inputs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
