# Generated by Django 6.0.7 on 2026-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_product_pricing_inputs"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="KIZUNA", max_length=100)),
                (
                    "company_name_ja",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "company_name_vi",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("address_ja", models.TextField(blank=True, default="")),
                ("address_vi", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mã số thuế / Tax ID",
                        max_length=50,
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True, default="", help_text="Footer note on invoice"
                    ),
                ),
                ("footer_text_ja", models.TextField(blank=True, default="")),
                ("footer_text_vi", models.TextField(blank=True, default="")),
                (
                    "bank_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Bank transfer info for invoice",
                    ),
                ),
                ("bank_info_ja", models.TextField(blank=True, default="")),
                ("bank_info_vi", models.TextField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo on invoice",
                        null=True,
                        upload_to="invoice/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Invoice Settings",
                "verbose_name_plural": "Invoice Settings",
            },
        ),
    ]
