# Generated by Django 6.0.7 on 2026-08-24 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_productreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order", "Order update"),
                            ("payment", "Payment"),
                            ("promo", "Promotion"),
                            ("cart", "Cart reminder"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Storefront path this notification points at, e.g. /order-history.",
                        max_length=200,
                    ),
                ),
                (
                    "action_label",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="shop_custom_user_id_15f688_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="shop_custom_user_id_47ddf6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dedupe_key__gt", "")),
                        fields=("user", "dedupe_key"),
                        name="unique_notification_dedupe_key",
                    )
                ],
            },
        ),
    ]
