# Generated by Django 6.0.7 on 2026-08-04 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_ai_integration_models'),
        ('shop', '0021_product_and_order_item_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(blank=True, default='unsubscribe', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketing_email_suppressions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('event', 'Event'), ('product', 'Product')], default='event', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially sent')], db_index=True, default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_campaigns', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='shop.product')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='admin_api.marketingcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketing_email_deliveries',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'email'), name='unique_campaign_recipient_email')],
            },
        ),
    ]
